<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download_1</name>
   <tag></tag>
   <elementGuidId>3b795375-ceea-43c3-b9a5-c14cb3ba221d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Download')])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) > td.Item > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c25325c9-d682-490a-8105-89eaeca8d7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>a/7z2201-x64.msi</value>
      <webElementGuid>3c24b731-dbce-49cf-ba01-bf8dfdfa5347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>b6c731be-eacf-4a6c-a5c3-41f3a37e94ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[5]/td[@class=&quot;Item&quot;]/a[1]</value>
      <webElementGuid>c1250789-5b4e-4a86-99bc-8a36cc69d145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[4]</value>
      <webElementGuid>23a6dc7f-0352-4706-9598-1518d751ebfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.exe'])[3]/following::a[1]</value>
      <webElementGuid>ab57f21e-8144-4bae-a8a5-28e66da62f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[6]/following::a[1]</value>
      <webElementGuid>bbd49dfa-a772-4ee8-8dc2-25049d387b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.msi'])[1]/preceding::a[1]</value>
      <webElementGuid>221093f7-0e74-4a9d-9175-010ecce97abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(alternative MSI installer) 7-Zip for 64-bit Windows x64 (Intel 64 or AMD64)'])[1]/preceding::a[1]</value>
      <webElementGuid>bdcca32e-188f-4fe5-a1e3-32514cefde3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'a/7z2201-x64.msi')]</value>
      <webElementGuid>cbe7429b-8dd8-4996-8456-547e0a9dde79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[5]/td/a</value>
      <webElementGuid>a5417633-6002-48ce-9818-d1e8359e9f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'a/7z2201-x64.msi' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>ab520d5d-2109-430c-95da-3d4ed6b0c96d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
